---
hostname: master.k8s.p4.greenpeace.org
hosttls: true
ingress:
  hosts:
    - name: release.k8s.p4.greenpeace.org
    - name: prod.p4.greenpeace.org
    - name: release.p4.greenpeace.org
    - name: prod.nginx.p4.greenpeace.org
nginxingress:
  hosts:
    - name: release.k8s.p4.greenpeace.org
      tls: true
    - name: prod.p4.greenpeace.org
      tls: true
    - name: release.p4.greenpeace.org
      tls: true
    - name: prod.nginx.p4.greenpeace.org
      tls: true
    - name: master.k8s.p4.greenpeace.org
      tls: true
