---
version: 2.1

docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth
  working_directory: /home/circleci/app

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint yaml
          command: make lint

  lint-worker:
    docker:
      - image: circleci/node:lts
        auth:
          <<: *docker_auth
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Lint worker
          command: ./node_modules/eslint/bin/eslint.js index.js

  tag:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: prepare git
          command: |
            git config user.email "${GIT_USER_EMAIL}"
            git config user.name "CircleCI Bot"
            git config merge.ours.driver true
      - run:
          name: tag
          command: |
            current_version=$(git-current-tag.sh)
            new_version=$(increment-version.sh $current_version)
            echo "Tagging to ${new_version}"
            git tag -a "$new_version" -m "$new_version"
            git push origin --tags

  deploy-worker:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Publish
          command: npx wrangler publish

workflows:
  branch:
    jobs:
      - lint
      - lint-worker
      - hold-promote:
          type: approval
          requires:
            - dev
          filters:
            branches:
              only: main
      - tag:
          context: org-global
          requires:
            - hold-promote
          filters:
            branches:
              only: main

  tag:
    jobs:
      - deploy-worker:
          context: cf-workers
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
